### ISSUE TITLE
Could parent and child be updated together?

### ISSUE THREAD

**Issue by ErinPo** [understrap/understrap-child#127]
Current parent version has bs4 final, but child is still on beta3.

**Comment by ErinPo** [comment]
Also, WP update version and Github version could be updated simultaneously.

Is there a particular reason why the child is not available through WP update?

**Comment by Nukium** [comment]
+1

**Comment by ErinPo** [comment]
I wonder if the author no longer cares for the child theme.

**Comment by eberhapa** [comment]
The child theme is just here to include all basic template files als structure. The child theme also deregisters all styles and scripts. You should manage the child theme yourself and get comfortable with npm. If the parent theme gets updated you have to update the child theme yourself. The parent theme for example includes all bootstrap files and fontawesome 4. What if you just need parts of bootstrap and fontawesome5? The child theme can't get updated like the parent theme because that would overwrite all your custom files. Further reading for updating packages [NPM update](https://docs.npmjs.com/cli/update)

**Comment by holger1411** [comment]
Yes, there is a good reason for using own dependencies for the child theme indipendently from the parent. It lets you rebuild your scripts and styles without the need to do it in the parent theme (which will make it un-updateable, which makes a child theme useless).

For example: You want to replace the default Bootstrap $primary color, you have to re-generate the css file from scss sources. If you change it in your child theme but you don´t have your own dependencies for generating the css file nothing will happen. If you change it in your parent theme you will loose this changes during an update.

So this way adds a clear border between parent and child theme. The child has its own independent dev and dependency stack. You can even replace Gulp with Grunt, npm with Bower etc. (that makes the child theme un-updateable, but not the parent)

**Comment by ErinPo** [comment]
Thanks @eberhapa and @holger1411, I appreciate the explanations. I will be looking to familiarize myself with one of those package managers when I get some time.

**Comment by blachawk** [comment]
@holger1411 while on topic, 
Does the UnderStrap team have any document resources online on how to update UnderStrap themes?  Something I go to every time when I need to push for a major release update?

**Comment by Thomas-A-Reinert** [comment]
Nope, not yet. As already commented in https://github.com/understrap/understrap/issues/654

**Comment by Thomas-A-Reinert** [comment]
All issues should be resolved. Feel free to reopen if any problem persists.
