### ISSUE TITLE
Referencing the $gray-* variables in _child_theme_variables.scss: undefined variable

### ISSUE THREAD

**Issue by bongoman** [understrap/understrap-child#13]
I'm trying to reference the $gray-lighter variable in my _child_theme_variables.scss file in the following way:

`$dropdown-bg:        $gray-lighter;`

but the SASS parser gives an undefined variable error.

**Comment by holger1411** [comment]
Hi!
The problem is that your _child_theme_variables.scss is loaded BEFORE the Bootstrap variables file:
/src/sass/bootstrap4/_variables.scss. That is necessary to provide values to overwrite the BS default variables.

Means you try to access a variable which isnt set at this time...
Check the child-themes.scss:
```
@import "theme/child_theme_variables";  // <--------- Add your variables into this file. Also add variables to overwrite Bootstrap variables here
@import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Change from /bootstrap3 to /bootstrap4 Watch out! just for testing in the moment! 
```

**Comment by IngoVals** [comment]
One solution would be to redefine the gray colors ( at least those you want to use ) in the `_child_theme_variables.scss `.
