### ISSUE TITLE
Bootstrap4 missing files for bootstrap4.scss

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap-child#158]
Please correct me if I am wrong, but the bootstrsap4.scss that ships with the child theme is making reference to specific imports like...

```
@import "../../src/sass/bootstrap4/custom";
@import "../../src/sass/bootstrap4/normalize";
@import "../../src/sass/bootstrap4/responsive-embed";
```
...but these files are not under the following directory
`\wp-content\themes\draft-understrap-child-theme_0.2.0\src\sass\bootstrap4`

...So as a result when I attempt to do a `gulp watch-bs` from my terminal, npm is complaining about missing files. For example this is one message I get

>  messageOriginal: File to import not found or unreadable: ../../src/sass/bootstrap4/custom.
    relativePath: sass\assets\bootstrap4.scss

In addition, there is no `@import "../../src/sass/bootstrap4/functions"; at the top of bootstrap4.scss`.  Why is that?

I must be doing something wrong, but don't know what...

**Comment by blachawk** [comment]
ahhhhh - for some reason, I have a Bootstrap v4.0.0-alpha.6 of bootstrap4.scss installed with my child theme.  But how did that happen?? I downloaded the child theme directly off the landing page for UnderStrap.  This is what my file looks like...


```
/*!
 * Bootstrap v4.0.0-alpha.6 (https://getbootstrap.com)
 * Copyright 2011-2017 The Bootstrap Authors
 * Copyright 2011-2017 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */

// Core variables and mixins
@import "../../src/sass/bootstrap4/variables";
@import "../../src/sass/bootstrap4/mixins";
@import "../../src/sass/bootstrap4/custom";

// Reset and dependencies
@import "../../src/sass/bootstrap4/normalize";
@import "../../src/sass/bootstrap4/print";

// Core CSS
@import "../../src/sass/bootstrap4/reboot";
@import "../../src/sass/bootstrap4/type";
@import "../../src/sass/bootstrap4/images";
@import "../../src/sass/bootstrap4/code";
@import "../../src/sass/bootstrap4/grid";
@import "../../src/sass/bootstrap4/tables";
@import "../../src/sass/bootstrap4/forms";
@import "../../src/sass/bootstrap4/buttons";

// Components
@import "../../src/sass/bootstrap4/transitions";
@import "../../src/sass/bootstrap4/dropdown";
@import "../../src/sass/bootstrap4/button-group";
@import "../../src/sass/bootstrap4/input-group";
@import "../../src/sass/bootstrap4/custom-forms";
@import "../../src/sass/bootstrap4/nav";
@import "../../src/sass/bootstrap4/navbar";
@import "../../src/sass/bootstrap4/card";
@import "../../src/sass/bootstrap4/breadcrumb";
@import "../../src/sass/bootstrap4/pagination";
@import "../../src/sass/bootstrap4/badge";
@import "../../src/sass/bootstrap4/jumbotron";
@import "../../src/sass/bootstrap4/alert";
@import "../../src/sass/bootstrap4/progress";
@import "../../src/sass/bootstrap4/media";
@import "../../src/sass/bootstrap4/list-group";
@import "../../src/sass/bootstrap4/responsive-embed";
@import "../../src/sass/bootstrap4/close";

// Components w/ JavaScript
@import "../../src/sass/bootstrap4/modal";
@import "../../src/sass/bootstrap4/tooltip";
@import "../../src/sass/bootstrap4/popover";
@import "../../src/sass/bootstrap4/carousel";

// Utility classes
@import "../../src/sass/bootstrap4/utilities";

```

That looks completely different from this file...
https://github.com/understrap/understrap-child/blob/master/sass/assets/bootstrap4.scss

**Comment by blachawk** [comment]
You are the man!  Thank you for helping me know that.  I pulled almost every hair out of my head.

**Comment by Thomas-A-Reinert** [comment]
As I said - you´re welcome. Trying our best to develop and support a worthy piece of a theme :)
(And yes we all know - there´s still enough space for improvement, but *hey*, this is how the story goes ;) )

**Comment by blachawk** [comment]
@Thomas-A-Reinert no rush on anything sense you and the team are working to deploy the best updated child version, but I do have a question - How will the rest of the world know where and when t the latest child theme is fully compatible with it's parent theme?  Where can I go to get notified?

Thanks

**Comment by axlright** [comment]
@blachawk Not sure I understand this question 

> How will the rest of the world know that this child theme is fully compatible with it's parent theme (0.8.2)? Where can I go to get notified?

You can always star the parent and child repos on GitHub -  you can sign up for the never ending stream of issue emails 😏

**Comment by blachawk** [comment]
@axlright you do have a point! Issue solved.

**Comment by Thomas-A-Reinert** [comment]
Don´t get me wrong at all, @blachawk , but could you do me a personal favour? And really - no offense intended. I´m just summarizing my personal perception, I am **NOT** speaking for team UnderStrap but just for myself!

Besides: the same goes for everyone else "whom the cap fits"..

**To give in:** I admit that the documentation - at the very moment *SUCKS*  - but we´re working on it as a focal point atm with high pressure and expect a first release to be published within two weeks at the latest.

In understrap-child repo, two issues within the past 3 days: https://github.com/understrap/understrap-child/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ablachawk+
A good amount of that could´ve been solved by reading the Readme.md or doing a little research.

In understrap-parent, 6 issues within the past  days: https://github.com/understrap/understrap/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ablachawk+
5/6 could´ve also been solved with a little research or some basic WordPress Theme Development knowledge.

But I don´t want to be disgraceful, so I´ll also mention the [one where you helped me individually](https://github.com/understrap/understrap/issues/645#issuecomment-381779404).

Some of those issues were resolved within hours by yourself because you did some research.

So what I´d like you to ask is: Could you do the research _before_ raising an issue? And maybe have 24hrs go by? Because many things settle once you dig into them..


This has several reasons:

- Open issues "_don´t look good_" for an open-source initiative. But that´s just a personal note. If there´s an issue. there´s an issue. In this case this is us/me "whom the cap fits". Maybe. After some investigation.
- Others may become "infected" or jump on the band-wagon.. For no reason..
- We´re _**not**_ commercial. We´re not getting _**paid**_ for providing assistance.
- "Team UnderStrap" is not like a hundred people - we´re just a handful developers who spend their spare time.
- So if *you* don´t want to investigate the basics - why should we take our leisure time to answer?
- Every _**second**_ that distracts us from improving/updating the code by answering unneccessary isues just delays a better/improved/updated version/documentation.

That being said: You´re still welcome posting issues and requesting help. Really. I mean it. And we´re also willing to help. But pls take yourself some time to evaluate. And evaluate if it´s a general WordPress Issue (which I´ll be closing at once from now on) or a UnderStrap issue. Thanks in advance!

Tings a gwan, Thomas ;)

**Comment by blachawk** [comment]
Thank you Thomas for allowing me to continue to post.  But I am not all that cheerful that you wlingy choice me as a public example of laziness to some degree, especially when 2 out of the 6 posts I asked were basic questions.   I do read the forms, I look over prior discussions, but maybe I have not reseachred every corner of world before asking a question. For me to fail in doing so before I ask a question is ok because I honesly enjoy a good conversation rather that putting all my hope on documentation from third party sources ( and not to mention which quite frequenty changes or gets updated simply because we deal with technology).  Please don't feel offended but to some degree I have to defend myself from your post. 

If you notice, I am closing out posts that I have recently found answers on. Yes the documentation sucks at the moment and yes I could always research on Google further, but I'm just like you, under a heavy deadline with little resources. Getting  a direct answer from the source is perhaps one of my best options at the moment.

Hey I respect the work you, the free service you are willing to out in, and hope you continue to improve US because I can't find any other BS4 framework for WP that has come as far as you guys have.  

All that I ask is if you don't see me as the annoying little critter on your github forums. I will keep an honest eye to researching my answers before quickly asking.  If I fail in finding a confident answer in my research, and ask on her, it's simply for confirmation purposes.  Please don't get offended from my response.  I wish you well.

**Comment by AskAlice** [comment]
oof you should really specify on the site that this child theme is not up to date, just wasted 40 mins now unbillable time because of this bug
