### ISSUE TITLE
 Call to undefined function understrap_categorized_blog() after updating Understrap Parent

### ISSUE THREAD

**Issue by misfist** [understrap/understrap-child#214]
After updating the Understrap parent theme from 0.8.7 to 0.8.8, I started getting an error in my custom child theme originating from the parent Understrap theme.

```
Uncaught Error: Call to undefined function understrap_categorized_blog() in /srv/www/metcouncil/wordpress/wp-content/themes/understrap/404.php:45
```

The issue seems to be due to changes made in the parent `functions.php`, which now uses `locate_template` to require files. The problem is that `locate_template` first looks in the child theme for the files, and my custom child theme has its own function files (sometimes) using the same paths. So, in this case, `understrap_categorized_blog()` can't be found because the function is in the parent `/inc/template-tags.php` file, but the `locate_template` only loads the child theme's `/inc/template-tags.php`, which doesn't contain that function. 

As a work-around, I can rename my child theme function files. However, I'm not sure that the parent theme should be loading child function files rather than it's own. At the very least, this should be called out as a breaking change.

ref: https://codex.wordpress.org/Function_Reference/locate_template
https://github.com/understrap/understrap/commit/9dacaa8cf54fa67d39dc758cce45ad779161cf68

**Comment by bacoords** [comment]
Although this issue is older, I will note that we've decided to use `get_theme_file_path()` for loading function files from the `/inc/` folder. This will continue to be an issue, and I think the best option in the future is to prefix any custom files you add to the `/inc/` folder in a child theme, if you don't want them to be _potentially_ overridden by a new file added to `/inc/`. So for example, you can make yours `/inc/child-template-tags.php` and then WordPress would always load your file AND the parent theme.
