### ISSUE TITLE
Multiple Domain child theme css access

### ISSUE THREAD

**Issue by yessunil** [understrap/understrap-child#217]
My 7 child theme in wp-content themes folder and i have a one main global css in that folder
but  child theme css not override in global css or not any changes when i run gulp watch command
there is only working default variables css, so how can i access other child theme in my child folder

Thanks..

**Comment by danemorgan** [comment]
If you are changing your CSS files directly Gulp may be overwriting them with the unaltered SCSS files immediately. The build process has changed several times since this issue was raised. I encourage you to get the latest code for both the parent and child themes and see if that helps. Also, instructions have been added to the read me document.
