### ISSUE TITLE
Am I supposed to copy templates from Understrap Main to Understrap Child (to override)?

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap-child#287]
I'm just wondering why all the templates from main aren't also included in the Understrap-Child Zip download by default...or if I'm doing this wrong.

I finally got Understrap Child `npm install`ed with gulp-sass working correctly with `gulp watch-bs` and fixed the infinite loop problem in the scripts task, so then I set about to modifying the templates and I see every single template I want to modify is buried in Understrap, so I am going to have to go copy it over to the corresponding location in Understrap-Child. I'm not complaining about this, it just was a red flag that I may be doing this wrong.

I don't understand why it's set up this way. The decision to use a child theme means we plan to override the parent theme, so I feel like I must not be understanding the way this is supposed to work. Is it just done this way so that the end user can decide how many theme files they want to override instead of overriding them all? Or is there some different way I should be doing this? It just seems like it will waste a lot of time to hunt down which template part I need to override next if I only grab them one at a time from Main.

**Comment by bacoords** [comment]
Hi @currentcreative 

The child theme method is pretty standard practice in WordPress. Typically your child theme is meant to inherit EVERYTHING from the parent theme, and then if you want to override a template or function, you find it in the parent theme and copy it over to the child theme. This allows you to continue to get updates from the parent theme without losing the work you've done in the child theme. If you started by copying EVERYTHING over, then even files you didn't modify would never get updates.

As an alternative, you can also just grab a copy of the main Understrap theme and modify that directly. It includes the same gulp workflow, so you can just turn it into your own custom theme. The important step is to make sure you disable any updates because those WILL overwrite your theme. Basically modify the theme directory and name to something other than Understrap and then go ahead and make any changes you'd like. 

There's pros/cons to each method for sure.

**Comment by currentcreative** [comment]
Thank you, yeah that makes sense. Glad to know I am doing it right, I just had a wrong idea about child themes pop into my head.
