### ISSUE TITLE
Feature/bs5 development -> src/sass/assets/understrap/_understrap.scss -> 44

### ISSUE THREAD

**Issue by schwarzpunkt** [understrap/understrap-child#303]
.screen-reader-text {
	@extend .sr-only;
}

should be
.screen-reader-text {
	@extend .visually-hidden ;
}

 https://getbootstrap.com/docs/5.0/migration/#helpers

**Comment by bacoords** [comment]
Agreed, although I might do this to support both versions:

```scss
.screen-reader-text {
  @extend .sr-only !optional ;
  @extend .visually-hidden !optional;
}
```

**Comment by bacoords** [comment]
Thanks again for pointing this out. We've ended up using `@include visually-hidden();`. You can see it in the `develop` branch, which should be released soon. 

I also learned that font-awesome has a mixin and class for `.sr-only`, which is why it didn't technically fail in the child starter theme (though would fail if you don't use font-awesome and comment it out).
