### ISSUE TITLE
Can't register new sidebar in inc/widgets

### ISSUE THREAD

**Issue by kbrookes** [understrap/understrap-child#96]
Hi there,

I've tried to register an additional sidebar by creating the /inc folder in understrap-child and copying the understrap /inc/widgets.php file to it.

I've tested by duplicating an existing sidebar with only a change or name. It works if I do this in understrap/inc/widgets.php, but not if I do it in understrap-child/inc/widgets.php.

I can add it in my functions.php file, but it puts it at the top of the list in the admin area, which is undesirable for this particular widget.

**Comment by radscheit** [comment]
I have the feeling that the childs ìnc` dir is ignored completely. Diy you tried to write it in your childs `functions.php`directly?

**Comment by Thomas-A-Reinert** [comment]
Well, we´re currently writing up the documentation for the parent as well as the child theme.

The solution for your problem is mentioned here: https://thomas-a-reinert.github.io/Understrap-Documentation/docs/0.8.2/extend/custom-widget-areas-sidebars/

Sidenote: Sorry for the super-late reply. I´ll close that for now as this definitely solves the problem.
Sidenote #2: Don´t bookmark that docu. It will move to a different place pretty soon. It´s just a preview in which we´re trying to solve some of the issues that came up by ppl like you. Thx for that!
